### ISSUE TITLE
Support for switching between profiles

### ISSUE THREAD

**Issue by tingiris** [twilio-labs/plugin-serverless#23]
After switching between profiles with the `profiles:use` command, `serverless:deploy` will still deploy to the profile that was active when the `serverless:init` command was run. 

My guess is that this is because the ACCOUNT_SID and AUTH_TOKEN get set in the .env file when`serverless:init` is run but don't get updated when the active profile is switched. 

Seems like the ACCOUNT_SID and AUTH_TOKEN values should be updated in the .env file when the `profiles:use` command is used to set a new active profile.

**Comment by dkundel** [comment]
Thanks for filing this issue @tingiris but this is intended. We need to add an entry in the docs explaining this but the order of credentials applied is the following (ordered by importance with 1. being the most important one):

1. Explicit credentials passed via `--account-sid` or `--auth-token`
2. Explicit profile passed via `--profile` or `-p` flag
3. `ACCOUNT_SID` and `AUTH_TOKEN` in the `.env` file
4. Implicit credentials from the `twilio` CLI. This internally prefers `TWILIO_ACCOUNT_SID` and `TWILIO_AUTH_TOKEN` over whatever profile you are using.

One of the reasons why we are doing this is because `npm run deploy` for example in a project will actually trigger `twilio-run deploy` which has no sense of the profiles of the Twilio CLI. The other reason is that we go in order of whatever is most explicit and an existing `.env` file in our opinion was more explicit that a separate command you might have executed before.

**Comment by tingiris** [comment]
Thanks for the explanation, @dkundel. That makes sense to me now.
