### ISSUE TITLE
Production env adds "undefined" suffix

### ISSUE THREAD

**Issue by michaelrkn** [twilio-labs/plugin-serverless#35]
Hi there. It used to be that if I ran `twilio serverless:deploy --production`, my project would be deployed to a domain like `project-1234.twil.io`. Today I ran this command for a new project for the first time in a bit, and my project was deployed to a domain like `project-1234-undefined.twil.io`. I compared this project and an old one from https://www.twilio.com/console/functions/api, and both have environments with `unique_name:
production`. Did something change? Do I need to run this differently? Or is this a bug? Thanks!

**Comment by philnash** [comment]
Huh, that sounds like a bug. Sorry about that! Will check into now.

**Comment by philnash** [comment]
I've investigated this in the serverless toolkit projects and I currently have the conclusion that this is an API problem. I'm going to take this up with the team internally and we'll get it fixed.

**Comment by philnash** [comment]
I had a flash of inspiration and I caught the bug. PR is here: https://github.com/twilio-labs/serverless-api/pull/50

**Comment by philnash** [comment]
This has been fixed! As the fix was in a dependency of this plugin, just updating the plugin won't work for now, but uninstalling and reinstalling the plugin will bring you up to up date.

Do the following:

```
twilio plugins:uninstall @twilio-labs/plugin-serverless
twilio plugins:install @twilio-labs/plugin-serverless
```

Then you can remove the old production environment with "undefined" in the name. You'll need to find the environment SID, which you can do with the CLI:

```
twilio api:serverless:v1:services:environments:list --service-sid YOUR_SERVICE_SID
twilio api:serverless:v1:services:environments:remove --service-sid YOUR_SERVICE_SID --sid ENVIRONMENT_SID
```

Then deploy to production fresh with:

```
twilio serverless:deploy --production
```

And your URL will not include "undefined".

**Comment by michaelrkn** [comment]
Thanks for fixing this!
